trigger:
  branches:
    include:
      - main

variables:
  appName: "adarsh-fish-store"   # Your Azure WebApp name
  resourceGroup: "OCEAN"          # Your Resource Group
  serviceConnection: "azure-connection" # Service connection name

stages:
  - stage: Build
    displayName: "Build Stage"
    jobs:
      - job: BuildJob
        pool:
          name: 'Adarsh-CI-CD'
          demands:
            - Agent.Name -equals agent2
        steps:
          - checkout: self
          - script: echo "Preparing static website files..."
            displayName: "Build Step"
          - task: CopyFiles@2
            inputs:
              SourceFolder: '$(Build.SourcesDirectory)'
              Contents: '**'
              TargetFolder: '$(Build.ArtifactStagingDirectory)'
          - task: PublishBuildArtifacts@1
            inputs:
              PathtoPublish: '$(Build.ArtifactStagingDirectory)'
              ArtifactName: 'drop'
              publishLocation: 'Container'

  - stage: Deploy
    displayName: "Deploy Stage"
    dependsOn: Build
    jobs:
      - deployment: DeployWeb
        displayName: "Deploy Web to Azure App Service"
        environment: 'dev'   # Add approvals here in Environments tab
        pool:
          name: 'Adarsh-CI-CD'
          demands:
            - Agent.Name -equals agent3
        strategy:
          runOnce:
            deploy:
              steps:
                - download: current
                  artifact: drop
                - task: AzureWebApp@1
                  inputs:
                    azureSubscription: '$(serviceConnection)'
                    appType: 'webApp'
                    appName: '$(appName)'
                    package: '$(Pipeline.Workspace)/drop'
